<a href="https://colab.research.google.com/github/Cceugene/Cceugene/blob/master/%5BNumPy%5Dnewaxis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
n = np.arange(1, 11)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
n[np.newaxis]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [5]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
n2 = np.newaxis
print(n2)

None


In [12]:
a = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]})
a

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [16]:
a['c'] = np.newaxis
a

a  b     c
0  1  5  None
1  2  6  None
2  3  7  None
3  4  8  None